name: EPG Update

on:
  push:
  schedule:
    - cron: 0 * * * *

# permissions:
#   contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: EPG Update
        run: |
          # http://epg.51zmt.top:8000/e.xml
          rm -f e.xml && wget https://epg.112114.xyz/pp.xml -O e.xml
          git config --global user.name Gj
          git config --global user.email gongjie0422@163.com
          git add e.xml
          git commit -m "Update e.xml"
          git push -f origin master
